DATASETNAME = 'CodexSmall'
EMBEDDING_VERSION = 1
EMBEDDING_TYPE = 'TransE'
# TransE DistMult PairRE RotatE
TESTNUMBER = 999#4+EMBEDDING_VERSION
NAME_OF_RUN = f"{DATASETNAME}_{TESTNUMBER}_{EMBEDDING_TYPE}"
SAVENAME = f"{DATASETNAME}_{EMBEDDING_VERSION}_{EMBEDDING_TYPE}"

AMOUNT_OF_SUBGRAPHS = 1000
SIZE_OF_SUBGRAPHS = 50
DIMENSIONS = 50
EPOCH_NMB = 400

DOSCORE = False
DODIS = False
DODIS_RELATION = False
DOFULLGRAPHLP = True
DO_F1 = True
DOSCORE_RELATION_BASED = False
DO_AVERAGE = False

COMPARISON_TO_RELATED = False
MORE_TRAIN = True

STORE_MODEL = True
LOAD_MODEL = True
LOAD_TRIPLES = True
LOAD_SUBGRAPHS = True

OUT_OF_BOX = False

LP_EMB_SPLIT = 0.5
TRAIN_TEST_SPLIT = 0.33
RESET_PROB = 0.2
SIGFIGS = 5
MAKE_TRAINING_SMALLER = False
SMALLER_RATIO = 0.5