DATASETNAME = 'Nations'
EMBEDDING_VERSION = 1
TESTNUMBER = 98
LP_EMB_SPLIT = 0.5
TRAIN_TEST_SPLIT = 0.33
RESET_PROB = 0.2
SIGFIGS = 5
AMOUNT_OF_SUBGRAPHS = 1000
SIZE_OF_SUBGRAPHS = 10
NAME_OF_RUN = f"{DATASETNAME}_{TESTNUMBER}"
SAVENAME = f"{DATASETNAME}_{EMBEDDING_VERSION}"

DO_THREE_BASED = True
STORE_MODEL = True
LOAD_MODEL = True
DOSCORE = True
DODIS = True
LOAD_TRIPLES = True
LOAD_SUBGRAPHS = True

DO_LABEL_BASED = False
DO_NOT_LABEL_BASED = True